# subject: Alec Sheffield
# Date of birth: 09/04/1995
# Height: 5 feet 7 inch
# Weight: 140
# Sex: male

title = 'rtSynth_rt'

session=4 # which session is this? which day is this on? could be 1 2 3 4 5 
subjectDay = 4
subjectIDforxnat="rtSynth_sub005_ses4" # PATIENTID has to be unique for each subject
preDay_YYYYMMDD="20210705" # can be "0" if there is no previous day for this session
YYYYMMDD="20210706" # 20210629 20210702 20210705 20210706 20210707 

subjectName = "sub005" # subject folder name in the rtSynth_rt/subjects folder
LASTNAME="rtSynth_sub005"
realtimeFolder_subjectName="rtSynth_sub005"

studyDescription="rtSynth_rt"

num_total_TRs=174 # number of total TRs in feedback session # 12*14+6=174
TrialNumber= 12 # feedback trial number for a feedback run.

runNum = [1] #[1,2,3,4,5,6,7,8] # This is the list of unique run, e.g. when the recognition1 is repeated twice, this can be 1 and 2
scanNum = [1] #[1,2,3,4,5,6,7,8] # This is a list of scan(or runs that might be repetitive)

plotTitle = 'Realtime Plot'
plotXLabel = 'Sample #'
plotYLabel = 'B prob'
plotXRangeLow = 0
plotXRangeHigh = 176
plotYRangeLow = 0
plotYRangeHigh = 20
plotAutoRangeX = false
plotAutoRangeY = true

minExpectedDicomSize=460000 #dicom folder: 465962 465922 465852 465880 465962 466168 local: 465922

trying=false