# subject Han Wan
# Date of birth: 02/24/1997
# Height: 5 feet 6 inch
# Weight: 110
# Sex: female

title = 'rtSynth_rt'

session=5 # which session is this? which day is this on? could be 1 2 3 4 5 
subjectDay = 5 #this is for the naming of web/conf/{subjactName}_day{subjectDay}_run{runNum}.toml
subjectIDforxnat="rtSynth_sub004_ses5" # PATIENTID has to be unique for each subject
preDay_YYYYMMDD="20210625" # can be "0" if there is no previous day for this session
YYYYMMDD="20210628" # 20210621 20210622 20210624 20210625 20210628

subjectName = "sub004" # subject folder name in the rtSynth_rt/subjects folder
LASTNAME="rtSynth_sub004"
realtimeFolder_subjectName="rtSynth_sub004"

studyDescription="rtSynth_rt"

num_total_TRs=174 # number of total TRs in feedback session # 12*14+6=174
TrialNumber= 12 # feedback trial number for a feedback run.

runNum = [1] #[1,2,3,4,5,6,7,8] # This is the list of unique run, e.g. when the recognition1 is repeated twice, this can be 1 and 2
scanNum = [1] #[1,2,3,4,5,6,7,8] # This is a list of scan(or runs that might be repetitive)

plotTitle = 'Realtime Plot'
plotXLabel = 'Sample #'
plotYLabel = 'B prob'
plotXRangeLow = 0
plotXRangeHigh = 176
plotYRangeLow = 0
plotYRangeHigh = 20
plotAutoRangeX = false
plotAutoRangeY = true
# dicomNamePattern = "001_{SCAN:06d}_{TR:06d}.dcm"
minExpectedDicomSize=460000 #dicom folder: 465962 465922 465852 465880 465962 466168 local: 465922

trying=false